### PR TITLE
Updated package and retrained models.

### PR DESCRIPTION
**Pull request by dimitrismistriotis**

### CODE REVIEW

**Comment by dimitrismistriotis** [comment]
@menkotoglou Strange behaviour with Python3.8. Scikit learn does not mention deprecation but version is not available. Code here essentially skips latest version... Do not know if we should deprecate it or not. My take is to leave things as-is perhaps with a note to README in case they did not include Python 3.8 by accident.

**Comment by dimitrismistriotis** [comment]
Resolves #33

**Review by menkotoglou — APPROVED** [review]
What does `....post1` stands for?

**Comment by menkotoglou** [comment]
Got it, good to go from my side

**Pull request merged**
